export enum RoleName {
  ADMIN = "ADMIN",
  KASSIR = "KASSIR",
  DOCTOR = "DOCTOR",
  HAMSHIRA = "HAMSHIRA",
  LABARANT = "LABARANT",
  DIAGNOST = "DIAGNOST",
  TEXNIK_HODIM = "TEXNIK_HODIM",
  DIREKTOR = "DIREKTOR",
  HISOBCHI = "HISOBCHI",
}
